src/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash

from .. import db # means from __init__.py
from ..models import User

auth = Blueprint('auth', __name__)

@auth.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(username=username).first()
        if user:
            flash('User already exists.', category='error')
        elif len(username) < 2:
            flash('username must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(username=username, password_hash=generate_password_hash(
                password1, method='pbkdf2:sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('tabs.wines'))

    return render_template('register.html', user=current_user)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user_username = User.query.filter_by(username=username).first()
        if user_username:
            if check_password_hash(user_username.password_hash, password):
                flash('Logged in successfully with username!', category='success')
                login_user(user_username, remember=True)
                return redirect(url_for('tabs.wines'))
            else:
                # print('username - wrong password')
                flash('Invalid username or password', category='error')
        else:
            flash('Invalid username or password', category='error')
            # print('username does not exist')

    return render_template('login.html', user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <script src="{{ url_for('static', filename='js/main.js') }}"></script>

        {% block additional_static_files %}{% endblock %}
        
        {% block page_title %}{% endblock %}
    </head>
    <body>
        <header id="page-header">
            <div id="left-header">
                <a id="title-link" class="header" href="{{ url_for('tabs.wines') }}">
                    <div id="title-logo-header">
                        <span id="title-header">WINEBASE</span>
                        <img src="{{url_for('static', filename='img/winebase-logo-small.png')}}" />
                    </div>
                </a>
                
                <div id="tabs-container">
                    {% block tabs %}{% endblock %}
                </div>
            </div>
        
            <!-- container for the drop down menu for the account information/logout, etc. -->
            <div id="right-header">
                {% if user.is_authenticated %}
                <h2 id="header-username">{{ username }}</h2>
                <div id="logout-button">
                    <a class="header" id="logout" href="{{ url_for('auth.logout') }}">LOGOUT</a>
                </div>
                {% endif %}
            </div>
        
        </header>
        <div id="body-content-header">
            <!-- Will only be visible for tab pages (not login/registration pages) -->
            <h2 id="body-content-header-title">{{ tab_name }}</h2>
            <!-- Add some content in the header per tab page if requested -->
            {% block body_content_header %}{% endblock %}
        </div>

        {% block content %}{% endblock %}

    </body>
</html>

src/templates/login.html
{% extends "base.html" %}

{% block content %}

<div class="login-register-container">
  <div class="form-container">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <form method="POST">
      <h3 class="login-register-title">Login</h3>
      <div class="form-group">
        <input
          type="text"
          class="form-control"
          id="username"
          name="username"
          placeholder="Enter username"
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <h4>Not a member? Register <a class="login-link" href="{{ url_for('auth.register') }}">here</a></h4>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
  </div>
</div>


{% endblock %}

src/templates/register.html
{% extends "base.html" %}

{% block content %}

<div class="login-register-container">
  <div class="form-container">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <form method="POST">
      <h3 class="login-register-title">Register</h3>
      <div class="form-group">
        <input
          type="text"
          class="form-control"
          id="username"
          name="username"
          placeholder="Enter username"
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          class="form-control"
          id="password1"
          name="password1"
          placeholder="Enter password"
        />
      </div>
      <div class="form-group">
        <input
          type="password"
          class="form-control"
          id="password2"
          name="password2"
          placeholder="Confirm password"
        />
      </div>
      <h4>Already a member? Login <a class="login-link" href="{{ url_for('auth.login') }}">here</a></h4>
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
</div>

{% endblock %}